const Company = require('../models/Company');
const Job = require('../models/Job');
const User = require('../models/User');

const companySeedData = [
  {
    companyName: 'TCS',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg',
    description:
      'Tata Consultancy Services is a global leader in IT services, consulting, and digital business solutions, conducting nationwide campus drives.',
    website: 'https://www.tcs.com',
    industry: 'IT Services & Consulting',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    fullAddress: 'TCS House, Raveline Street, Fort, Mumbai, Maharashtra 400001, India',
    officeAddress: 'TCS House, Raveline Street, Fort, Mumbai – 400001',
    interviewVenue: 'Auditorium Hall A, Central Placement Complex / TCS iON Platform',
    jobLocations: ['Mumbai', 'Bangalore', 'Hyderabad', 'Pune', 'Chennai'],
    workModes: ['On-site', 'Hybrid'],
    totalVacancies: 180,
    hiringCount: 520,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 35, year: 2025 },
      { month: 'Nov 2025', hired: 42, year: 2025 },
      { month: 'Dec 2025', hired: 28, year: 2025 },
      { month: 'Jan 2026', hired: 50, year: 2026 },
      { month: 'Feb 2026', hired: 65, year: 2026 },
      { month: 'Mar 2026', hired: 55, year: 2026 },
      { month: 'Apr 2026', hired: 48, year: 2026 },
      { month: 'May 2026', hired: 38, year: 2026 },
      { month: 'Jun 2026', hired: 30, year: 2026 },
      { month: 'Jul 2026', hired: 22, year: 2026 },
      { month: 'Aug 2026', hired: 18, year: 2026 },
      { month: 'Sep 2026', hired: 19, year: 2026 },
    ],
    jobs: [
      {
        title: 'Systems Engineer - Digital & Prime Cadre',
        description: 'Design and deploy resilient enterprise applications with cloud native and microservices architectures.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'TCS Think Campus, Electronic City, Bangalore',
        interviewVenue: 'Auditorium Hall A / Microsoft Teams Virtual Hall',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹7.0 - ₹9.5 LPA',
        vacancies: 95,
        hiredCount: 290,
        requiredSkills: ['Java', 'Python', 'Spring Boot', 'SQL', 'Data Structures'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE', 'ME'],
        minimumCGPA: 6.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 30),
      },
      {
        title: 'Cloud & AI Engineer - Ninja Cadre',
        description: 'Engineer full stack cloud solutions, CI/CD automation, and intelligent enterprise integrations.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'TCS Synergy Park, Gachibowli, Hyderabad',
        interviewVenue: 'Placement Block 2 / Virtual Interview Pods',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹4.5 - ₹6.0 LPA',
        vacancies: 85,
        hiredCount: 230,
        requiredSkills: ['React', 'Node.js', 'AWS', 'Docker', 'REST APIs'],
        eligibleDepartments: ['CSE', 'ECE', 'CIVIL', 'ME'],
        minimumCGPA: 6.0,
        maximumBacklogs: 1,
        applicationDeadline: new Date(2026, 10, 15),
      },
    ],
  },
  {
    companyName: 'Infosys',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg',
    description:
      'Infosys is a global leader in next-generation digital services and consulting, enabling clients across 56 countries to navigate digital transformation.',
    website: 'https://www.infosys.com',
    industry: 'IT Services & Consulting',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    fullAddress: 'Infosys Limited, Electronics City, Hosur Road, Bangalore, Karnataka 560100, India',
    officeAddress: 'Electronics City, Hosur Road, Bangalore – 560100',
    interviewVenue: 'Smart Campus Auditorium 1 / Infosys InfyTQ Online Portal',
    jobLocations: ['Bangalore', 'Pune', 'Hyderabad', 'Chennai', 'Mysore'],
    workModes: ['On-site', 'Hybrid'],
    totalVacancies: 150,
    hiringCount: 410,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 30, year: 2025 },
      { month: 'Nov 2025', hired: 38, year: 2025 },
      { month: 'Dec 2025', hired: 25, year: 2025 },
      { month: 'Jan 2026', hired: 45, year: 2026 },
      { month: 'Feb 2026', hired: 58, year: 2026 },
      { month: 'Mar 2026', hired: 48, year: 2026 },
      { month: 'Apr 2026', hired: 40, year: 2026 },
      { month: 'May 2026', hired: 32, year: 2026 },
      { month: 'Jun 2026', hired: 26, year: 2026 },
      { month: 'Jul 2026', hired: 20, year: 2026 },
      { month: 'Aug 2026', hired: 14, year: 2026 },
      { month: 'Sep 2026', hired: 16, year: 2026 },
    ],
    jobs: [
      {
        title: 'Specialist Programmer (Power Programmer)',
        description: 'Elite programming cadre focused on deep competitive coding, distributed data architectures, and algorithms.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Infosys Electronics City, Bangalore',
        interviewVenue: 'Campus Tech Center, Hall C',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹9.5 - ₹12.5 LPA',
        vacancies: 60,
        hiredCount: 160,
        requiredSkills: ['Algorithms', 'Java', 'Python', 'Competitive Coding', 'System Design'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 7.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 28),
      },
      {
        title: 'Digital Specialist Engineer (DSE)',
        description: 'Deliver agile digital transformations, modern web apps, and machine learning pipelines.',
        location: 'Pune, Maharashtra',
        officeAddress: 'Hinjewadi Infotech Park, Phase II, Pune',
        interviewVenue: 'Virtual Assessment Hall 4',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹6.25 - ₹7.5 LPA',
        vacancies: 90,
        hiredCount: 250,
        requiredSkills: ['JavaScript', 'React', 'Node.js', 'SQL', 'Git'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 6.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 10),
      },
    ],
  },
  {
    companyName: 'Wipro',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Wipro_Primary_Logo_Color_RGB.svg',
    description:
      'Wipro Limited is a leading technology services and consulting company focused on building innovative solutions addressing complex digital transformation needs.',
    website: 'https://www.wipro.com',
    industry: 'IT Services & Consulting',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    fullAddress: 'Doddakannelli, Sarjapur Road, Bangalore, Karnataka 560035, India',
    officeAddress: 'Sarjapur Road, Doddakannelli, Bangalore – 560035',
    interviewVenue: 'Placement Seminar Hall 2 / Wipro Elite NLTH Online Platform',
    jobLocations: ['Bangalore', 'Chennai', 'Hyderabad', 'Pune', 'Noida'],
    workModes: ['Hybrid', 'On-site'],
    totalVacancies: 110,
    hiringCount: 340,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 22, year: 2025 },
      { month: 'Nov 2025', hired: 28, year: 2025 },
      { month: 'Dec 2025', hired: 18, year: 2025 },
      { month: 'Jan 2026', hired: 35, year: 2026 },
      { month: 'Feb 2026', hired: 45, year: 2026 },
      { month: 'Mar 2026', hired: 40, year: 2026 },
      { month: 'Apr 2026', hired: 32, year: 2026 },
      { month: 'May 2026', hired: 26, year: 2026 },
      { month: 'Jun 2026', hired: 20, year: 2026 },
      { month: 'Jul 2026', hired: 15, year: 2026 },
      { month: 'Aug 2026', hired: 12, year: 2026 },
      { month: 'Sep 2026', hired: 14, year: 2026 },
    ],
    jobs: [
      {
        title: 'Project Engineer - Turbo Cadre',
        description: 'Accelerated engineering cadre working on enterprise SaaS, DevOps automation, and micro-frontend architectures.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'Wipro Technologies, Gachibowli, Hyderabad',
        interviewVenue: 'Main Placement Cell, Room 104',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹6.5 - ₹8.0 LPA',
        vacancies: 60,
        hiredCount: 180,
        requiredSkills: ['C++', 'Java', 'Data Structures', 'Linux', 'SQL'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 6.8,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 25),
      },
      {
        title: 'Software Developer - Elite National Talent',
        description: 'Build enterprise-grade web applications, automated test harnesses, and client APIs.',
        location: 'Chennai, Tamil Nadu',
        officeAddress: 'ELCOT SEZ, Sholinganallur, Chennai',
        interviewVenue: 'Virtual Assessment Suite A',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹4.0 - ₹5.5 LPA',
        vacancies: 50,
        hiredCount: 160,
        requiredSkills: ['Java', 'Python', 'Web Fundamentals', 'RDBMS'],
        eligibleDepartments: ['CSE', 'ECE', 'ME', 'CIVIL'],
        minimumCGPA: 6.0,
        maximumBacklogs: 1,
        applicationDeadline: new Date(2026, 10, 5),
      },
    ],
  },
  {
    companyName: 'HCLTech',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/74/HCL_Tech_logo.svg',
    description:
      'HCLTech is a global technology company, home to 220,000+ people across 60 countries, delivering industry-leading capabilities centered around digital, engineering, and cloud.',
    website: 'https://www.hcltech.com',
    industry: 'IT Services & Consulting',
    location: 'Noida, Uttar Pradesh',
    city: 'Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    fullAddress: 'Plot No. 3A, Sector 126, Noida, Uttar Pradesh 201304, India',
    officeAddress: 'Sector 126, Noida Expressway, Noida – 201304',
    interviewVenue: 'Campus Placement Lab 3 / HCL First Careers Online Suite',
    jobLocations: ['Noida', 'Bangalore', 'Chennai', 'Hyderabad', 'Lucknow'],
    workModes: ['Hybrid', 'On-site'],
    totalVacancies: 95,
    hiringCount: 290,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 18, year: 2025 },
      { month: 'Nov 2025', hired: 24, year: 2025 },
      { month: 'Dec 2025', hired: 15, year: 2025 },
      { month: 'Jan 2026', hired: 30, year: 2026 },
      { month: 'Feb 2026', hired: 38, year: 2026 },
      { month: 'Mar 2026', hired: 34, year: 2026 },
      { month: 'Apr 2026', hired: 28, year: 2026 },
      { month: 'May 2026', hired: 22, year: 2026 },
      { month: 'Jun 2026', hired: 18, year: 2026 },
      { month: 'Jul 2026', hired: 14, year: 2026 },
      { month: 'Aug 2026', hired: 10, year: 2026 },
      { month: 'Sep 2026', hired: 12, year: 2026 },
    ],
    jobs: [
      {
        title: 'Graduate Engineer Trainee - Cloud & Infra',
        description: 'Support mission-critical cloud migrations, automation scripting, and telecom network software.',
        location: 'Noida, Uttar Pradesh',
        officeAddress: 'HCL Technology Hub, Sector 126, Noida',
        interviewVenue: 'Seminar Hall 3 / Teams Virtual Pod',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹4.75 - ₹6.25 LPA',
        vacancies: 55,
        hiredCount: 165,
        requiredSkills: ['Python', 'Linux', 'Networking', 'Cloud Basics', 'Shell Scripting'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 6.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 22),
      },
      {
        title: 'Associate Software Developer - Product Engineering',
        description: 'Build modern embedded software, IoT stacks, and high-performance backend pipelines.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'HCL SEZ, Jigani Industrial Area, Bangalore',
        interviewVenue: 'Placement Block A, Interview Room 2',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹6.0 - ₹7.5 LPA',
        vacancies: 40,
        hiredCount: 125,
        requiredSkills: ['C', 'C++', 'Data Structures', 'Git', 'OS Concepts'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 7.0,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 8),
      },
    ],
  },
  {
    companyName: 'Tech Mahindra',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Tech_Mahindra_New_Logo.svg',
    description:
      'Tech Mahindra represents the connected world, offering innovative and customer-centric information technology experiences to over 1,200 global clients.',
    website: 'https://www.techmahindra.com',
    industry: 'IT Services & Consulting',
    location: 'Pune, Maharashtra',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    fullAddress: 'Plot No. 1, Rajiv Gandhi Infotech Park, Hinjewadi, Phase III, Pune, Maharashtra 411057, India',
    officeAddress: 'Rajiv Gandhi Infotech Park, Hinjewadi Phase III, Pune',
    interviewVenue: 'College Auditorium Block B / Tech Mahindra Virtual Hall',
    jobLocations: ['Pune', 'Hyderabad', 'Bangalore', 'Chennai', 'Chandigarh'],
    workModes: ['Hybrid', 'On-site'],
    totalVacancies: 80,
    hiringCount: 260,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 16, year: 2025 },
      { month: 'Nov 2025', hired: 20, year: 2025 },
      { month: 'Dec 2025', hired: 14, year: 2025 },
      { month: 'Jan 2026', hired: 28, year: 2026 },
      { month: 'Feb 2026', hired: 35, year: 2026 },
      { month: 'Mar 2026', hired: 30, year: 2026 },
      { month: 'Apr 2026', hired: 25, year: 2026 },
      { month: 'May 2026', hired: 20, year: 2026 },
      { month: 'Jun 2026', hired: 16, year: 2026 },
      { month: 'Jul 2026', hired: 12, year: 2026 },
      { month: 'Aug 2026', hired: 8, year: 2026 },
      { month: 'Sep 2026', hired: 10, year: 2026 },
    ],
    jobs: [
      {
        title: 'Associate Software Engineer - Next-Gen Services',
        description: 'Develop next-generation telecom software, cloud integrations, and enterprise web solutions.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'Tech Mahindra Infocity, Madhapur, Hyderabad',
        interviewVenue: 'Placement Hall 1 / Online Assessment',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹4.5 - ₹5.5 LPA',
        vacancies: 50,
        hiredCount: 160,
        requiredSkills: ['Java', 'SQL', 'JavaScript', 'Problem Solving'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE', 'ME'],
        minimumCGPA: 6.0,
        maximumBacklogs: 1,
        applicationDeadline: new Date(2026, 9, 26),
      },
      {
        title: 'Digital Solutions Engineer',
        description: 'Design generative AI interfaces, analytics dashboards, and automated business workflows.',
        location: 'Pune, Maharashtra',
        officeAddress: 'Tech Mahindra Hinjewadi Phase III, Pune',
        interviewVenue: 'Auditorium Hall B',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹6.0 - ₹7.25 LPA',
        vacancies: 30,
        hiredCount: 100,
        requiredSkills: ['Python', 'React', 'FastAPI', 'Machine Learning Basics'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 6.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 12),
      },
    ],
  },
  {
    companyName: 'Accenture',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Accenture.svg',
    description:
      'Accenture is a leading global professional services company that helps the world’s leading businesses, governments and other organizations build their digital core.',
    website: 'https://www.accenture.com',
    industry: 'Management & IT Consulting',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    fullAddress: 'IBC Knowledge Park, Bannerghatta Main Rd, Bangalore, Karnataka 560029, India',
    officeAddress: 'IBC Knowledge Park, 4/1, Bannerghatta Main Rd, Bangalore',
    interviewVenue: 'Main Auditorium / Accenture Discovery Online Portal',
    jobLocations: ['Bangalore', 'Hyderabad', 'Gurgaon', 'Pune', 'Mumbai', 'Kolkata'],
    workModes: ['Hybrid', 'Remote'],
    totalVacancies: 140,
    hiringCount: 460,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 32, year: 2025 },
      { month: 'Nov 2025', hired: 40, year: 2025 },
      { month: 'Dec 2025', hired: 28, year: 2025 },
      { month: 'Jan 2026', hired: 48, year: 2026 },
      { month: 'Feb 2026', hired: 62, year: 2026 },
      { month: 'Mar 2026', hired: 52, year: 2026 },
      { month: 'Apr 2026', hired: 44, year: 2026 },
      { month: 'May 2026', hired: 36, year: 2026 },
      { month: 'Jun 2026', hired: 28, year: 2026 },
      { month: 'Jul 2026', hired: 22, year: 2026 },
      { month: 'Aug 2026', hired: 16, year: 2026 },
      { month: 'Sep 2026', hired: 18, year: 2026 },
    ],
    jobs: [
      {
        title: 'Advanced Application Engineering Analyst',
        description: 'Lead modern cloud microservices development, DevOps automation, and high-velocity digital products.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Prestige Technostar, Whitefield, Bangalore',
        interviewVenue: 'Auditorium Hall A / Teams Live Interview',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹6.5 - ₹8.5 LPA',
        vacancies: 80,
        hiredCount: 260,
        requiredSkills: ['Java', 'Spring', 'Cloud Architecture', 'Angular / React', 'SQL'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 6.8,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 29),
      },
      {
        title: 'Associate Software Engineer (ASE)',
        description: 'Build enterprise application logic, optimize API performance, and deliver client innovations.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'Accenture Campus, Hitec City, Hyderabad',
        interviewVenue: 'Placement Block C, Room 301',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹4.5 - ₹5.4 LPA',
        vacancies: 60,
        hiredCount: 200,
        requiredSkills: ['Problem Solving', 'Java', 'Python Basics', 'Web Tech'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE', 'CIVIL', 'ME'],
        minimumCGPA: 6.0,
        maximumBacklogs: 1,
        applicationDeadline: new Date(2026, 10, 15),
      },
    ],
  },
  {
    companyName: 'Cognizant',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Cognizant_logo_2022.svg',
    description:
      'Cognizant engineers modern businesses to improve everyday life, modernizing technology, reimagining processes and transforming experiences.',
    website: 'https://www.cognizant.com',
    industry: 'IT Services & Consulting',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    fullAddress: 'DLF Cybercity, Manapakkam, Chennai, Tamil Nadu 600125, India',
    officeAddress: 'DLF Cybercity, 1/124 Mount Poonamallee Road, Manapakkam, Chennai',
    interviewVenue: 'Campus Central Hall / Cognizant Superset Campus Drive',
    jobLocations: ['Chennai', 'Bangalore', 'Coimbatore', 'Hyderabad', 'Kolkata', 'Pune'],
    workModes: ['On-site', 'Hybrid'],
    totalVacancies: 130,
    hiringCount: 420,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 28, year: 2025 },
      { month: 'Nov 2025', hired: 35, year: 2025 },
      { month: 'Dec 2025', hired: 22, year: 2025 },
      { month: 'Jan 2026', hired: 42, year: 2026 },
      { month: 'Feb 2026', hired: 55, year: 2026 },
      { month: 'Mar 2026', hired: 46, year: 2026 },
      { month: 'Apr 2026', hired: 38, year: 2026 },
      { month: 'May 2026', hired: 30, year: 2026 },
      { month: 'Jun 2026', hired: 24, year: 2026 },
      { month: 'Jul 2026', hired: 18, year: 2026 },
      { month: 'Aug 2026', hired: 12, year: 2026 },
      { month: 'Sep 2026', hired: 15, year: 2026 },
    ],
    jobs: [
      {
        title: 'Programmer Analyst Trainee (GenC Next)',
        description: 'Advanced engineering role focused on high performance distributed programming, full stack React/Node, and AWS services.',
        location: 'Chennai, Tamil Nadu',
        officeAddress: 'Cognizant MEPZ Campus, Tambaram, Chennai',
        interviewVenue: 'Main Placement Cell, Hall 1',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹6.75 - ₹9.0 LPA',
        vacancies: 65,
        hiredCount: 210,
        requiredSkills: ['Data Structures', 'Python', 'Java', 'Full Stack', 'Cloud'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 7.0,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 27),
      },
      {
        title: 'GenC Developer Trainee',
        description: 'Build enterprise workflow automation, database queries, and functional business software modules.',
        location: 'Coimbatore, Tamil Nadu',
        officeAddress: 'CHIL SEZ, Saravanampatti, Coimbatore',
        interviewVenue: 'Virtual Hall 2',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹4.0 - ₹5.0 LPA',
        vacancies: 65,
        hiredCount: 210,
        requiredSkills: ['Java', 'SQL', 'HTML/CSS/JS', 'Agile Principles'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE', 'ME'],
        minimumCGPA: 6.0,
        maximumBacklogs: 1,
        applicationDeadline: new Date(2026, 10, 10),
      },
    ],
  },
  {
    companyName: 'Capgemini',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Capgemini_Logo.svg',
    description:
      'Capgemini is a global business and technology transformation partner, helping organizations to accelerate their dual transition towards a digital and sustainable world.',
    website: 'https://www.capgemini.com',
    industry: 'IT Services & Consulting',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    fullAddress: 'Plant 2, Godrej & Boyce Complex, Vikhroli (W), Mumbai, Maharashtra 400079, India',
    officeAddress: 'Godrej & Boyce Complex, LBS Marg, Vikhroli (W), Mumbai',
    interviewVenue: 'Campus Conference Center / Capgemini Virtual Assessment Hall',
    jobLocations: ['Mumbai', 'Bangalore', 'Pune', 'Hyderabad', 'Chennai'],
    workModes: ['Hybrid', 'On-site'],
    totalVacancies: 105,
    hiringCount: 330,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 20, year: 2025 },
      { month: 'Nov 2025', hired: 26, year: 2025 },
      { month: 'Dec 2025', hired: 16, year: 2025 },
      { month: 'Jan 2026', hired: 34, year: 2026 },
      { month: 'Feb 2026', hired: 44, year: 2026 },
      { month: 'Mar 2026', hired: 38, year: 2026 },
      { month: 'Apr 2026', hired: 30, year: 2026 },
      { month: 'May 2026', hired: 24, year: 2026 },
      { month: 'Jun 2026', hired: 18, year: 2026 },
      { month: 'Jul 2026', hired: 14, year: 2026 },
      { month: 'Aug 2026', hired: 10, year: 2026 },
      { month: 'Sep 2026', hired: 12, year: 2026 },
    ],
    jobs: [
      {
        title: 'Senior Analyst - Digital Engineering',
        description: 'Design resilient microservices, distributed backends, and responsive cloud interfaces.',
        location: 'Pune, Maharashtra',
        officeAddress: 'Capgemini SEZ, Talwade, Pune',
        interviewVenue: 'Placement Auditorium Hall B',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹7.5 - ₹9.0 LPA',
        vacancies: 50,
        hiredCount: 160,
        requiredSkills: ['Java 17', 'Spring Boot', 'React', 'PostgreSQL', 'Docker'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 7.0,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 25),
      },
      {
        title: 'Analyst Software Engineer',
        description: 'Develop and maintain enterprise applications, automate build pipelines, and write integration tests.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Capgemini Knowledge Park, Whitefield, Bangalore',
        interviewVenue: 'Tech Cell Room 2',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹4.25 - ₹5.5 LPA',
        vacancies: 55,
        hiredCount: 170,
        requiredSkills: ['C++', 'Java', 'SQL', 'Git', 'Agile'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE', 'CIVIL', 'ME'],
        minimumCGPA: 6.2,
        maximumBacklogs: 1,
        applicationDeadline: new Date(2026, 10, 8),
      },
    ],
  },
  {
    companyName: 'IBM',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg',
    description:
      'IBM is a leading global cloud and cognitive solutions company, with innovation at the core of AI, quantum computing, and hybrid cloud technology.',
    website: 'https://www.ibm.com',
    industry: 'Enterprise Software & Cloud',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    fullAddress: 'Manyata Embassy Business Park, Hebbal, Outer Ring Road, Bangalore, Karnataka 560045, India',
    officeAddress: 'Manyata Embassy Business Park, Outer Ring Road, Bangalore',
    interviewVenue: 'Main Auditorium / IBM Webex Virtual Drive',
    jobLocations: ['Bangalore', 'Hyderabad', 'Pune', 'Gurgaon', 'Kochi'],
    workModes: ['Hybrid', 'Remote'],
    totalVacancies: 85,
    hiringCount: 280,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 16, year: 2025 },
      { month: 'Nov 2025', hired: 22, year: 2025 },
      { month: 'Dec 2025', hired: 14, year: 2025 },
      { month: 'Jan 2026', hired: 28, year: 2026 },
      { month: 'Feb 2026', hired: 36, year: 2026 },
      { month: 'Mar 2026', hired: 32, year: 2026 },
      { month: 'Apr 2026', hired: 26, year: 2026 },
      { month: 'May 2026', hired: 20, year: 2026 },
      { month: 'Jun 2026', hired: 16, year: 2026 },
      { month: 'Jul 2026', hired: 12, year: 2026 },
      { month: 'Aug 2026', hired: 8, year: 2026 },
      { month: 'Sep 2026', hired: 10, year: 2026 },
    ],
    jobs: [
      {
        title: 'Associate System Engineer - Hybrid Cloud & AI',
        description: 'Engineer Red Hat OpenShift deployments, containerized microservices, and enterprise AI orchestration.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'IBM India, Manyata Tech Park, Bangalore',
        interviewVenue: 'Placement Block A, Suite 3',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹7.2 - ₹9.8 LPA',
        vacancies: 50,
        hiredCount: 160,
        requiredSkills: ['Linux', 'Kubernetes', 'Python', 'Java', 'Cloud Native'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 7.2,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 30),
      },
      {
        title: 'Software Developer - Watson & Data Platforms',
        description: 'Build backend pipelines, enterprise NLP models, and real-time data streaming architectures.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'IBM India, Hitec City, Hyderabad',
        interviewVenue: 'IBM Virtual Interview Hall',
        jobType: 'Full Time',
        workMode: 'Remote',
        salary: '₹8.0 - ₹11.0 LPA',
        vacancies: 35,
        hiredCount: 120,
        requiredSkills: ['Python', 'SQL', 'FastAPI', 'Kafka', 'Data Engineering'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 7.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 18),
      },
    ],
  },
  {
    companyName: 'Microsoft',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg',
    description:
      'Microsoft empowers every person and every organization on the planet to achieve more through innovative cloud computing, developer platforms, and generative AI systems.',
    website: 'https://careers.microsoft.com',
    industry: 'Software & Cloud Technology',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    fullAddress: 'Microsoft India (R&D) Pvt Ltd, Gachibowli, Hyderabad, Telangana 500032, India',
    officeAddress: 'Microsoft Campus, Gachibowli, Hyderabad – 500032',
    interviewVenue: 'Campus Central Auditorium / Microsoft Teams Technical Interview Rooms',
    jobLocations: ['Hyderabad', 'Bangalore', 'Noida', 'Remote'],
    workModes: ['Remote', 'Hybrid'],
    totalVacancies: 75,
    hiringCount: 180,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 16, year: 2025 },
      { month: 'Nov 2025', hired: 18, year: 2025 },
      { month: 'Dec 2025', hired: 14, year: 2025 },
      { month: 'Jan 2026', hired: 28, year: 2026 },
      { month: 'Feb 2026', hired: 34, year: 2026 },
      { month: 'Mar 2026', hired: 30, year: 2026 },
      { month: 'Apr 2026', hired: 22, year: 2026 },
      { month: 'May 2026', hired: 18, year: 2026 },
      { month: 'Jun 2026', hired: 12, year: 2026 },
      { month: 'Jul 2026', hired: 8, year: 2026 },
      { month: 'Aug 2026', hired: 5, year: 2026 },
      { month: 'Sep 2026', hired: 5, year: 2026 },
    ],
    jobs: [
      {
        title: 'Software Engineer - Azure Core & Developer Tools',
        description: 'Build hyperscale cloud infrastructure, low-latency microservices, and AI computing primitives.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'Microsoft Campus, Gachibowli, Hyderabad',
        interviewVenue: 'Auditorium Hall A',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹22.0 - ₹32.0 LPA',
        vacancies: 45,
        hiredCount: 110,
        requiredSkills: ['C#', 'C++', 'System Design', 'Algorithms', 'Azure'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 8.0,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 20),
      },
      {
        title: 'Cloud Solution Architect Trainee',
        description: 'Collaborate with enterprise leaders to architect secure, scalable cloud backends and AI copilots.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Microsoft Prestige Ferns, Bellandur, Bangalore',
        interviewVenue: 'Virtual Pod 1',
        jobType: 'Full Time',
        workMode: 'Remote',
        salary: '₹16.0 - ₹24.0 LPA',
        vacancies: 30,
        hiredCount: 70,
        requiredSkills: ['Cloud Infrastructure', 'Python', 'DevOps', 'Security'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 7.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 5),
      },
    ],
  },
  {
    companyName: 'Google',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
    description:
      "Google's mission is to organize the world's information and make it universally accessible and useful through world-class search, Android, Cloud, and AI systems.",
    website: 'https://careers.google.com',
    industry: 'Internet & Deep Technology',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    fullAddress: 'Google India, Bagmane Constellation Business Park, Marathahalli, Bangalore, Karnataka 560037, India',
    officeAddress: 'Bagmane Constellation Business Park, Marathahalli, Bangalore',
    interviewVenue: 'Main Auditorium / Google Meet Technical Interview Rounds',
    jobLocations: ['Bangalore', 'Hyderabad', 'Gurgaon', 'Pune'],
    workModes: ['Hybrid', 'Remote'],
    totalVacancies: 50,
    hiringCount: 130,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 12, year: 2025 },
      { month: 'Nov 2025', hired: 15, year: 2025 },
      { month: 'Dec 2025', hired: 10, year: 2025 },
      { month: 'Jan 2026', hired: 22, year: 2026 },
      { month: 'Feb 2026', hired: 28, year: 2026 },
      { month: 'Mar 2026', hired: 24, year: 2026 },
      { month: 'Apr 2026', hired: 20, year: 2026 },
      { month: 'May 2026', hired: 16, year: 2026 },
      { month: 'Jun 2026', hired: 12, year: 2026 },
      { month: 'Jul 2026', hired: 9, year: 2026 },
      { month: 'Aug 2026', hired: 6, year: 2026 },
      { month: 'Sep 2026', hired: 6, year: 2026 },
    ],
    jobs: [
      {
        title: 'Associate Software Engineer (SWE)',
        description: 'Build high-scale distributed systems and algorithms reaching billions of global users.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Google Bagmane Constellation Business Park, Bangalore',
        interviewVenue: 'Auditorium Hall A / Google Meet Rooms',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹26.0 - ₹38.0 LPA',
        vacancies: 30,
        hiredCount: 80,
        requiredSkills: ['C++', 'Python', 'Data Structures & Algorithms', 'Distributed Systems'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 8.2,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 18),
      },
      {
        title: 'Cloud Solutions Engineer',
        description: 'Architect customer-facing cloud pipelines, machine learning workloads, and serverless backends.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'Google India, Hitec City, Hyderabad',
        interviewVenue: 'Placement Tech Room 1',
        jobType: 'Full Time',
        workMode: 'Remote',
        salary: '₹20.0 - ₹28.0 LPA',
        vacancies: 20,
        hiredCount: 50,
        requiredSkills: ['GCP', 'Kubernetes', 'Python', 'Networking', 'Go'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 7.8,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 2),
      },
    ],
  },
  {
    companyName: 'Amazon',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
    description:
      'Amazon is guided by four principles: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking.',
    website: 'https://www.amazon.jobs',
    industry: 'E-commerce & Cloud Computing',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    fullAddress: 'Amazon Development Centre India, Nanakramguda, Gachibowli, Hyderabad, Telangana 500032, India',
    officeAddress: 'Amazon Campus, Nanakramguda, Financial District, Hyderabad',
    interviewVenue: 'Main Auditorium / Amazon Chime Technical Interview Loop',
    jobLocations: ['Hyderabad', 'Bangalore', 'Chennai', 'Delhi NCR', 'Pune'],
    workModes: ['Hybrid', 'On-site'],
    totalVacancies: 90,
    hiringCount: 240,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 18, year: 2025 },
      { month: 'Nov 2025', hired: 22, year: 2025 },
      { month: 'Dec 2025', hired: 15, year: 2025 },
      { month: 'Jan 2026', hired: 32, year: 2026 },
      { month: 'Feb 2026', hired: 40, year: 2026 },
      { month: 'Mar 2026', hired: 35, year: 2026 },
      { month: 'Apr 2026', hired: 28, year: 2026 },
      { month: 'May 2026', hired: 22, year: 2026 },
      { month: 'Jun 2026', hired: 16, year: 2026 },
      { month: 'Jul 2026', hired: 12, year: 2026 },
      { month: 'Aug 2026', hired: 8, year: 2026 },
      { month: 'Sep 2026', hired: 10, year: 2026 },
    ],
    jobs: [
      {
        title: 'Software Development Engineer I (SDE 1)',
        description: 'Build planet-scale AWS services, e-commerce retail engines, and high throughput data pipelines.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'Amazon Campus, Financial District, Hyderabad',
        interviewVenue: 'Auditorium Hall B / Amazon Chime Room',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹24.0 - ₹34.0 LPA',
        vacancies: 50,
        hiredCount: 140,
        requiredSkills: ['Java', 'C++', 'Data Structures', 'OOP', 'System Design'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 8.0,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 21),
      },
      {
        title: 'Quality Assurance Engineer (QAE)',
        description: 'Design robust automated testing frameworks, load stress pipelines, and continuous verification bots.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Amazon World Trade Center, Malleshwaram, Bangalore',
        interviewVenue: 'Placement Tech Room 4',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹14.0 - ₹19.0 LPA',
        vacancies: 40,
        hiredCount: 100,
        requiredSkills: ['Python', 'Selenium', 'Java', 'Test Automation', 'API Testing'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 7.2,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 6),
      },
    ],
  },
  {
    companyName: 'Oracle',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/50/Oracle_logo.svg',
    description:
      'Oracle is a cloud technology company that provides organizations around the world with computing infrastructure and software to help them innovate, unlock efficiencies and become more effective.',
    website: 'https://www.oracle.com',
    industry: 'Enterprise Software & Database',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    fullAddress: 'Oracle Technology Park, Bannerghatta Main Rd, Bangalore, Karnataka 560029, India',
    officeAddress: 'Oracle Technology Park, Bannerghatta Road, Bangalore',
    interviewVenue: 'Campus Central Hall / Oracle Zoom Virtual Pods',
    jobLocations: ['Bangalore', 'Hyderabad', 'Noida', 'Pune'],
    workModes: ['Hybrid', 'Remote'],
    totalVacancies: 70,
    hiringCount: 220,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 14, year: 2025 },
      { month: 'Nov 2025', hired: 18, year: 2025 },
      { month: 'Dec 2025', hired: 12, year: 2025 },
      { month: 'Jan 2026', hired: 25, year: 2026 },
      { month: 'Feb 2026', hired: 32, year: 2026 },
      { month: 'Mar 2026', hired: 28, year: 2026 },
      { month: 'Apr 2026', hired: 22, year: 2026 },
      { month: 'May 2026', hired: 18, year: 2026 },
      { month: 'Jun 2026', hired: 14, year: 2026 },
      { month: 'Jul 2026', hired: 10, year: 2026 },
      { month: 'Aug 2026', hired: 8, year: 2026 },
      { month: 'Sep 2026', hired: 9, year: 2026 },
    ],
    jobs: [
      {
        title: 'Associate Applications Developer - OCI',
        description: 'Build Oracle Cloud Infrastructure (OCI) serverless components, autonomous database connectors, and microservices.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Oracle Technology Park, Bangalore',
        interviewVenue: 'Seminar Hall 1',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹14.0 - ₹19.5 LPA',
        vacancies: 40,
        hiredCount: 130,
        requiredSkills: ['Java', 'SQL', 'Data Structures', 'REST APIs', 'Cloud Computing'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 7.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 24),
      },
      {
        title: 'Cloud DevOps & Systems Trainee',
        description: 'Deploy Kubernetes clusters, monitor telemetry observability, and automate infrastructure deployments.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'Oracle Financial Services, Hitec City, Hyderabad',
        interviewVenue: 'Virtual Assessment Room 2',
        jobType: 'Full Time',
        workMode: 'Remote',
        salary: '₹11.0 - ₹15.0 LPA',
        vacancies: 30,
        hiredCount: 90,
        requiredSkills: ['Terraform', 'Linux', 'Python', 'Docker', 'GitOps'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 7.0,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 14),
      },
    ],
  },
  {
    companyName: 'Deloitte',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/56/Deloitte.svg',
    description:
      'Deloitte drives impact across industries, providing audit, consulting, financial advisory, risk management, and tax services to selected clients worldwide.',
    website: 'https://www.deloitte.com',
    industry: 'Consulting & Enterprise Technology',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    fullAddress: 'Deloitte Towers, Hitec City, Gachibowli, Hyderabad, Telangana 500081, India',
    officeAddress: 'Deloitte Towers, Hitec City, Gachibowli, Hyderabad',
    interviewVenue: 'Main Auditorium / Deloitte Talent Zoom Sessions',
    jobLocations: ['Hyderabad', 'Bangalore', 'Mumbai', 'Gurgaon', 'Pune'],
    workModes: ['Hybrid', 'On-site'],
    totalVacancies: 95,
    hiringCount: 310,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 20, year: 2025 },
      { month: 'Nov 2025', hired: 25, year: 2025 },
      { month: 'Dec 2025', hired: 18, year: 2025 },
      { month: 'Jan 2026', hired: 35, year: 2026 },
      { month: 'Feb 2026', hired: 44, year: 2026 },
      { month: 'Mar 2026', hired: 38, year: 2026 },
      { month: 'Apr 2026', hired: 30, year: 2026 },
      { month: 'May 2026', hired: 24, year: 2026 },
      { month: 'Jun 2026', hired: 18, year: 2026 },
      { month: 'Jul 2026', hired: 14, year: 2026 },
      { month: 'Aug 2026', hired: 10, year: 2026 },
      { month: 'Sep 2026', hired: 12, year: 2026 },
    ],
    jobs: [
      {
        title: 'Associate Analyst - Technology Consulting',
        description: 'Provide enterprise ERP customization, full-stack enterprise automation, and cyber risk technical assessment.',
        location: 'Hyderabad, Telangana',
        officeAddress: 'Deloitte Towers, Gachibowli, Hyderabad',
        interviewVenue: 'Auditorium Hall B',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹7.6 - ₹9.5 LPA',
        vacancies: 55,
        hiredCount: 180,
        requiredSkills: ['Python', 'SQL', 'Java', 'Analytics', 'Business Systems'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 6.8,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 28),
      },
      {
        title: 'Cyber Risk & Cloud Security Analyst',
        description: 'Conduct security vulnerability scanning, IAM role design, and cloud compliance audits.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Deloitte Tech Center, Bellandur, Bangalore',
        interviewVenue: 'Placement Tech Room 3',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹6.5 - ₹8.0 LPA',
        vacancies: 40,
        hiredCount: 130,
        requiredSkills: ['Cybersecurity', 'Networking', 'Python', 'Cloud Security'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 6.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 11),
      },
    ],
  },
  {
    companyName: 'LTIMindtree',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/LTIMindtree_Logo.svg',
    description:
      'LTIMindtree is a global technology consulting and digital solutions company that enables enterprises across industries to reimagine business models, accelerate innovation, and maximize growth.',
    website: 'https://www.ltimindtree.com',
    industry: 'IT Services & Digital Consulting',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    fullAddress: 'L&T House, Ballard Estate, Mumbai, Maharashtra 400001, India',
    officeAddress: 'Mindtree Park, Global Village, RVCE Post, Mysore Road, Bangalore',
    interviewVenue: 'Placement Seminar Hall 1 / LTIMindtree Test Pods',
    jobLocations: ['Mumbai', 'Bangalore', 'Chennai', 'Hyderabad', 'Pune'],
    workModes: ['Hybrid', 'On-site'],
    totalVacancies: 90,
    hiringCount: 290,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 18, year: 2025 },
      { month: 'Nov 2025', hired: 24, year: 2025 },
      { month: 'Dec 2025', hired: 16, year: 2025 },
      { month: 'Jan 2026', hired: 32, year: 2026 },
      { month: 'Feb 2026', hired: 40, year: 2026 },
      { month: 'Mar 2026', hired: 35, year: 2026 },
      { month: 'Apr 2026', hired: 28, year: 2026 },
      { month: 'May 2026', hired: 22, year: 2026 },
      { month: 'Jun 2026', hired: 18, year: 2026 },
      { month: 'Jul 2026', hired: 14, year: 2026 },
      { month: 'Aug 2026', hired: 10, year: 2026 },
      { month: 'Sep 2026', hired: 11, year: 2026 },
    ],
    jobs: [
      {
        title: 'Graduate Engineer Trainee - Edge & Digital Core',
        description: 'Build modern responsive enterprise applications, cloud native APIs, and telemetry pipelines.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Mindtree Park, Mysore Road, Bangalore',
        interviewVenue: 'Placement Block B, Hall 2',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹5.5 - ₹7.0 LPA',
        vacancies: 50,
        hiredCount: 160,
        requiredSkills: ['Java', 'React', 'Node.js', 'Postgres', 'Git'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 6.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 23),
      },
      {
        title: 'Data & Cloud Associate',
        description: 'Construct scalable ETL workflows, data lake transformations, and business intelligence dashboards.',
        location: 'Pune, Maharashtra',
        officeAddress: 'LTIMindtree Hinjewadi Phase 1, Pune',
        interviewVenue: 'Virtual Assessment Suite',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹5.0 - ₹6.5 LPA',
        vacancies: 40,
        hiredCount: 130,
        requiredSkills: ['Python', 'SQL', 'Snowflake Basics', 'Power BI'],
        eligibleDepartments: ['CSE', 'ECE', 'CIVIL', 'ME'],
        minimumCGPA: 6.0,
        maximumBacklogs: 1,
        applicationDeadline: new Date(2026, 10, 4),
      },
    ],
  },
  {
    companyName: 'Mphasis',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Mphasis_Logo.svg',
    description:
      'Mphasis is a leading applied technology services company, delivering hyper-personalized experiences and driving agile business operations.',
    website: 'https://www.mphasis.com',
    industry: 'Applied Technology & IT Services',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    fullAddress: 'Bagmane World Technology Center, Marathahalli Ring Rd, Bangalore, Karnataka 560048, India',
    officeAddress: 'Bagmane World Technology Center, Outer Ring Road, Bangalore',
    interviewVenue: 'Seminar Hall 4 / Mphasis Online Assessment Hub',
    jobLocations: ['Bangalore', 'Pune', 'Chennai', 'Hyderabad'],
    workModes: ['Hybrid', 'On-site'],
    totalVacancies: 65,
    hiringCount: 210,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 12, year: 2025 },
      { month: 'Nov 2025', hired: 16, year: 2025 },
      { month: 'Dec 2025', hired: 10, year: 2025 },
      { month: 'Jan 2026', hired: 22, year: 2026 },
      { month: 'Feb 2026', hired: 28, year: 2026 },
      { month: 'Mar 2026', hired: 25, year: 2026 },
      { month: 'Apr 2026', hired: 20, year: 2026 },
      { month: 'May 2026', hired: 15, year: 2026 },
      { month: 'Jun 2026', hired: 12, year: 2026 },
      { month: 'Jul 2026', hired: 8, year: 2026 },
      { month: 'Aug 2026', hired: 6, year: 2026 },
      { month: 'Sep 2026', hired: 7, year: 2026 },
    ],
    jobs: [
      {
        title: 'Associate Software Engineer - Fintech Solutions',
        description: 'Develop banking payment integrations, regulatory data processing modules, and API security layers.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Bagmane World Tech Center, Bangalore',
        interviewVenue: 'Seminar Hall 4',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹4.5 - ₹5.8 LPA',
        vacancies: 65,
        hiredCount: 210,
        requiredSkills: ['Java', 'Oracle SQL', 'Spring Boot', 'REST APIs'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE'],
        minimumCGPA: 6.0,
        maximumBacklogs: 1,
        applicationDeadline: new Date(2026, 9, 29),
      },
    ],
  },
  {
    companyName: 'Persistent Systems',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Persistent_Systems_Logo.svg',
    description:
      'Persistent Systems is a trusted global solutions partner delivering digital business acceleration, enterprise modernization, and next-gen product engineering.',
    website: 'https://www.persistent.com',
    industry: 'Digital Product Engineering',
    location: 'Pune, Maharashtra',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    fullAddress: 'Bhageerath, 402, Senapati Bapat Road, Pune, Maharashtra 411016, India',
    officeAddress: 'Persistent Hinjewadi Phase 1, Hinjewadi, Pune',
    interviewVenue: 'Placement Tech Room 2 / Persistent Virtual Hackathon',
    jobLocations: ['Pune', 'Bangalore', 'Hyderabad', 'Nagpur', 'Goa'],
    workModes: ['Hybrid', 'Remote'],
    totalVacancies: 70,
    hiringCount: 230,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 14, year: 2025 },
      { month: 'Nov 2025', hired: 18, year: 2025 },
      { month: 'Dec 2025', hired: 12, year: 2025 },
      { month: 'Jan 2026', hired: 25, year: 2026 },
      { month: 'Feb 2026', hired: 32, year: 2026 },
      { month: 'Mar 2026', hired: 28, year: 2026 },
      { month: 'Apr 2026', hired: 22, year: 2026 },
      { month: 'May 2026', hired: 18, year: 2026 },
      { month: 'Jun 2026', hired: 14, year: 2026 },
      { month: 'Jul 2026', hired: 10, year: 2026 },
      { month: 'Aug 2026', hired: 8, year: 2026 },
      { month: 'Sep 2026', hired: 9, year: 2026 },
    ],
    jobs: [
      {
        title: 'Software Engineer - Product Engineering',
        description: 'Build high-performance microservices, multi-tenant cloud platforms, and modern React interfaces.',
        location: 'Pune, Maharashtra',
        officeAddress: 'Persistent Hinjewadi Campus, Pune',
        interviewVenue: 'Placement Auditorium Hall B',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹6.5 - ₹8.5 LPA',
        vacancies: 70,
        hiredCount: 230,
        requiredSkills: ['Java', 'Python', 'React', 'Data Structures', 'Docker'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 6.8,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 27),
      },
    ],
  },
  {
    companyName: 'Zoho',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Zoho_Corporation_logo.svg',
    description:
      'Zoho Corporation is a leading Indian multinational technology company that makes computer software and web-based business tools, powering 100M+ users globally.',
    website: 'https://www.zoho.com',
    industry: 'Cloud Software & SaaS',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    fullAddress: 'Estancia IT Park, Plot No. 140 & 151, GST Road, Vallancherry, Chengalpattu, Tamil Nadu 603202, India',
    officeAddress: 'Zoho Estancia IT Park, GST Road, Chennai',
    interviewVenue: 'Main Auditorium / Zoho Schools & Campus Evaluation Center',
    jobLocations: ['Chennai', 'Tenkasi', 'Coimbatore', 'Salem', 'Tirunelveli'],
    workModes: ['On-site'],
    totalVacancies: 85,
    hiringCount: 270,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 15, year: 2025 },
      { month: 'Nov 2025', hired: 20, year: 2025 },
      { month: 'Dec 2025', hired: 14, year: 2025 },
      { month: 'Jan 2026', hired: 28, year: 2026 },
      { month: 'Feb 2026', hired: 36, year: 2026 },
      { month: 'Mar 2026', hired: 32, year: 2026 },
      { month: 'Apr 2026', hired: 25, year: 2026 },
      { month: 'May 2026', hired: 20, year: 2026 },
      { month: 'Jun 2026', hired: 16, year: 2026 },
      { month: 'Jul 2026', hired: 12, year: 2026 },
      { month: 'Aug 2026', hired: 10, year: 2026 },
      { month: 'Sep 2026', hired: 12, year: 2026 },
    ],
    jobs: [
      {
        title: 'Member Technical Staff (Software Developer)',
        description: 'Design from-scratch data storage engines, low-level web protocols, and high-concurrency SaaS applications.',
        location: 'Chennai, Tamil Nadu',
        officeAddress: 'Zoho Estancia IT Park, GST Road, Chennai',
        interviewVenue: 'Auditorium Hall A / Zoho Offline Problem Solving Round',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹8.0 - ₹12.0 LPA',
        vacancies: 55,
        hiredCount: 180,
        requiredSkills: ['C', 'Java', 'Data Structures', 'Algorithmic Problem Solving', 'Web Architecture'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE', 'ME', 'CIVIL'],
        minimumCGPA: 6.0,
        maximumBacklogs: 2,
        applicationDeadline: new Date(2026, 9, 23),
      },
      {
        title: 'Technical Support Engineer & Solutions Architect',
        description: 'Troubleshoot complex enterprise integrations, automate customer webhooks, and resolve API diagnostics.',
        location: 'Tenkasi, Tamil Nadu',
        officeAddress: 'Zoho Rural Tech Campus, Tenkasi',
        interviewVenue: 'Placement Tech Room 1',
        jobType: 'Full Time',
        workMode: 'On-site',
        salary: '₹5.5 - ₹7.0 LPA',
        vacancies: 30,
        hiredCount: 90,
        requiredSkills: ['Networking', 'JavaScript', 'SQL', 'API Integrations'],
        eligibleDepartments: ['CSE', 'ECE', 'EEE', 'CIVIL', 'ME'],
        minimumCGPA: 6.0,
        maximumBacklogs: 2,
        applicationDeadline: new Date(2026, 10, 5),
      },
    ],
  },
  {
    companyName: 'Freshworks',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Freshworks_inc_logo.svg',
    description:
      'Freshworks makes business software people love to use, purpose-built for IT, customer support, sales, and marketing teams to power modern customer delight.',
    website: 'https://www.freshworks.com',
    industry: 'SaaS & Enterprise Product',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    fullAddress: 'Global Infocity Park, 40 MGR Salai, Perungudi, Chennai, Tamil Nadu 600096, India',
    officeAddress: 'Block B, Global Infocity Park, Perungudi, Chennai',
    interviewVenue: 'Placement Seminar Hall 2 / Freshworks Tech Assessment Hall',
    jobLocations: ['Chennai', 'Bangalore', 'Remote'],
    workModes: ['Hybrid', 'Remote'],
    totalVacancies: 60,
    hiringCount: 190,
    companySize: 'Enterprise',
    isVerified: true,
    monthlyHiringData: [
      { month: 'Oct 2025', hired: 12, year: 2025 },
      { month: 'Nov 2025', hired: 15, year: 2025 },
      { month: 'Dec 2025', hired: 10, year: 2025 },
      { month: 'Jan 2026', hired: 22, year: 2026 },
      { month: 'Feb 2026', hired: 28, year: 2026 },
      { month: 'Mar 2026', hired: 24, year: 2026 },
      { month: 'Apr 2026', hired: 20, year: 2026 },
      { month: 'May 2026', hired: 16, year: 2026 },
      { month: 'Jun 2026', hired: 12, year: 2026 },
      { month: 'Jul 2026', hired: 8, year: 2026 },
      { month: 'Aug 2026', hired: 6, year: 2026 },
      { month: 'Sep 2026', hired: 7, year: 2026 },
    ],
    jobs: [
      {
        title: 'Associate Software Engineer - Frontend & Core SaaS',
        description: 'Build customer-facing CRM modules, responsive React/Ember design systems, and real-time chat widgets.',
        location: 'Chennai, Tamil Nadu',
        officeAddress: 'Global Infocity Park, Perungudi, Chennai',
        interviewVenue: 'Seminar Hall 2 / Zoom Round',
        jobType: 'Full Time',
        workMode: 'Hybrid',
        salary: '₹12.0 - ₹16.0 LPA',
        vacancies: 35,
        hiredCount: 110,
        requiredSkills: ['JavaScript', 'React', 'Ruby on Rails / Node.js', 'CSS/HTML5', 'REST APIs'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 7.2,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 9, 22),
      },
      {
        title: 'Platform Infrastructure Engineer',
        description: 'Operate multi-region AWS Kubernetes clusters, database replication shards, and zero-downtime deployments.',
        location: 'Bangalore, Karnataka',
        officeAddress: 'Freshworks Koramangala, Bangalore',
        interviewVenue: 'Placement Tech Room 3',
        jobType: 'Full Time',
        workMode: 'Remote',
        salary: '₹14.0 - ₹18.5 LPA',
        vacancies: 25,
        hiredCount: 80,
        requiredSkills: ['AWS', 'Kubernetes', 'Python', 'Terraform', 'Observability'],
        eligibleDepartments: ['CSE', 'ECE'],
        minimumCGPA: 7.5,
        maximumBacklogs: 0,
        applicationDeadline: new Date(2026, 10, 2),
      },
    ],
  },
];

const seedCompaniesAndJobs = async () => {
  try {
    // Find or create default recruiter user
    let defaultRecruiter = await User.findOne({ role: 'recruiter' });
    if (!defaultRecruiter) {
      defaultRecruiter = await User.findOne();
    }

    for (const cData of companySeedData) {
      const { jobs, ...companyFields } = cData;

      let company = await Company.findOne({ companyName: companyFields.companyName });

      if (!company) {
        company = await Company.create({
          ...companyFields,
          recruiterId: defaultRecruiter?._id || null,
        });
        console.log(`Seeded company: ${company.companyName} (${company.totalVacancies} vacancies)`);
      } else {
        // Ensure vacancies, hiring count, interview venue, office address, and monthly hiring data are kept up to date
        company.totalVacancies = companyFields.totalVacancies;
        company.hiringCount = companyFields.hiringCount;
        company.monthlyHiringData = companyFields.monthlyHiringData;
        company.jobLocations = companyFields.jobLocations;
        company.workModes = companyFields.workModes;
        company.logo = companyFields.logo;
        company.description = companyFields.description;
        company.officeAddress = companyFields.officeAddress;
        company.fullAddress = companyFields.fullAddress;
        company.interviewVenue = companyFields.interviewVenue;
        company.industry = companyFields.industry;
        company.location = companyFields.location;
        await company.save();
      }

      // Check and seed jobs for this company
      for (const jobData of jobs) {
        const existingJob = await Job.findOne({
          companyId: company._id,
          title: jobData.title,
        });

        if (!existingJob) {
          await Job.create({
            ...jobData,
            companyId: company._id,
            recruiterId: defaultRecruiter?._id || null,
            status: 'Approved',
          });
          console.log(`  Seeded job: ${jobData.title}`);
        } else {
          existingJob.vacancies = jobData.vacancies;
          existingJob.hiredCount = jobData.hiredCount;
          existingJob.salary = jobData.salary;
          existingJob.requiredSkills = jobData.requiredSkills;
          existingJob.eligibleDepartments = jobData.eligibleDepartments;
          existingJob.minimumCGPA = jobData.minimumCGPA;
          existingJob.maximumBacklogs = jobData.maximumBacklogs;
          existingJob.applicationDeadline = jobData.applicationDeadline;
          existingJob.officeAddress = jobData.officeAddress || company.officeAddress;
          existingJob.interviewVenue = jobData.interviewVenue || company.interviewVenue;
          existingJob.status = 'Approved';
          await existingJob.save();
        }
      }
    }
    console.log(`Successfully seeded/updated all ${companySeedData.length} enterprise software companies and campus jobs.`);
  } catch (error) {
    console.error('Error seeding company data:', error.message);
  }
};

module.exports = { seedCompaniesAndJobs, companySeedData };
